# Generated by Django 4.0.4 on 2022-12-25 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_message_alter_cart_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('mini_description', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('date', models.DateField(default=datetime.datetime(2022, 12, 26, 3, 8, 45, 95569))),
                ('author', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 3, 8, 45, 95569)),
        ),
    ]
