# Generated by Django 4.0.4 on 2022-12-29 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_alter_blog_date_alter_cart_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('logo1', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('last_name', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('doljnost', models.CharField(blank=True, max_length=300)),
                ('facebook_link', models.CharField(blank=True, max_length=300)),
                ('instagram_link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 11, 15, 4, 981216)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 11, 15, 4, 979216)),
        ),
    ]
