# Generated by Django 4.0.4 on 2023-01-22 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_info_alter_blog_date_alter_cart_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nagrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.datetime(2023, 1, 22, 15, 28, 27, 590299))),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 22, 15, 28, 27, 590299)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 15, 28, 27, 590299)),
        ),
    ]
